import '../../../../core/pdf/models/receipt_pdf_data.dart';
import '../../../hostel/domain/entities/hostel_entity.dart';
import '../../domain/entities/receipt_entity.dart';

/// Converts receipt presentation data into the PDF layer's neutral model.
class ReceiptPdfDataMapper {
  const ReceiptPdfDataMapper();

  ReceiptPdfData map({
    required ReceiptEntity receipt,
    HostelEntity? hostel,
  }) {
    final receiptNumber = receipt.receiptNumber.trim();

    return ReceiptPdfData(
      title: 'Payment Receipt',
      documentNumber: receiptNumber.isEmpty
          ? 'Payment-${receipt.paymentId}'
          : receiptNumber,
      issuedAt: receipt.issuedAt,
      businessName: hostel?.name ?? 'Hostel Management',
      businessAddress: hostel?.address,
      businessPhone: hostel?.phone,
      recipientName: 'Payment ID: ${receipt.paymentId}',
      recipientDetails: 'Payment method: ${receipt.paymentMethodSnapshot}',
      lineItems: <ReceiptPdfLineItem>[
        ReceiptPdfLineItem(
          description: 'Payment received',
          detail: receipt.paymentMethodSnapshot,
          amount: receipt.paymentAmountSnapshot,
        ),
      ],
      totalLabel: 'TOTAL PAID',
      totalAmount: receipt.paymentAmountSnapshot,
      notes:
          'Receipt generated: ${_formatDateTime(receipt.createdAt)}\n'
          'Thank you for your payment.\n'
          'Generated by Hostel Management App.',
    );
  }

  String fileName(ReceiptEntity receipt) {
    final number = receipt.receiptNumber.trim();
    final identifier = number.isEmpty ? 'Payment_${receipt.paymentId}' : number;
    return 'Receipt_$identifier.pdf';
  }

  String _formatDateTime(DateTime value) =>
      '${_twoDigits(value.day)}/${_twoDigits(value.month)}/${value.year} '
      '${_twoDigits(value.hour)}:${_twoDigits(value.minute)}';

  String _twoDigits(int value) => value.toString().padLeft(2, '0');
}
