import 'dart:typed_data';

import '../../../../core/pdf/models/report_pdf_data.dart';
import '../cubit/profit_loss_state.dart';
import '../cubit/reports_date_filter.dart';

/// Converts the current Profit & Loss presentation state into export-ready PDF
/// data without exposing feature entities to the core PDF layer.
class ProfitLossPdfDataMapper {
  const ProfitLossPdfDataMapper();

  ReportPdfData map({
    required ProfitLossState state,
    required String hostelName,
    Uint8List? logoBytes,
  }) {
    final data = state.data;
    if (data == null) {
      throw StateError('Profit and loss data is unavailable for export.');
    }

    final generatedAt = DateTime.now();
    final totalRevenue = data.totalRevenue;
    return ReportPdfData(
      title: 'Profit & Loss Report',
      organizationName: hostelName,
      logoBytes: logoBytes,
      periodLabel: _periodLabel(state),
      generatedAt: generatedAt,
      summary: <ReportPdfSummaryItem>[
        ReportPdfSummaryItem(
          label: 'Total Revenue',
          value: _money(totalRevenue),
        ),
        ReportPdfSummaryItem(
          label: 'Total Expenses',
          value: _money(data.totalExpenses),
        ),
        ReportPdfSummaryItem(
          label: 'Net Profit',
          value: _money(data.netProfit),
        ),
        ReportPdfSummaryItem(
          label: 'Profit Margin',
          value: '${data.profitMargin.toStringAsFixed(1)}%',
        ),
      ],
      sections: <ReportPdfTableSection>[
        ReportPdfTableSection(
          title: 'Revenue Breakdown',
          headers: const <String>['Source', 'Amount', 'Percentage'],
          rows: <List<String>>[
            _breakdownRow('Rent Income', data.rentRevenue, totalRevenue),
            _breakdownRow(
              'Damage Charges',
              data.damageChargeRevenue,
              totalRevenue,
            ),
            _breakdownRow('Other Income', data.otherRevenue, totalRevenue),
          ],
        ),
        ReportPdfTableSection(
          title: 'Expense Breakdown',
          headers: const <String>['Category', 'Amount', 'Percentage'],
          rows: <List<String>>[
            _breakdownRow(
              'Operational Expenses',
              data.totalExpenses,
              data.totalExpenses,
            ),
          ],
        ),
      ],
      footerNote:
          'Generated by Hostel Management App\nGenerated: ${_timestamp(generatedAt)}',
    );
  }

  String fileName(ProfitLossState state) =>
      'Profit_Loss_${_filePeriodLabel(state)}.pdf';

  List<String> _breakdownRow(String label, double value, double total) =>
      <String>[
        label,
        _money(value),
        '${total <= 0 ? 0 : (value / total * 100).toStringAsFixed(1)}%',
      ];

  String _money(double value) => 'INR ${value.toStringAsFixed(2)}';

  String _periodLabel(ProfitLossState state) {
    if (state.activeFilter == ReportsDateFilter.custom &&
        state.customFrom != null &&
        state.customTo != null) {
      return '${_date(state.customFrom!)} - ${_date(state.customTo!)}';
    }
    return state.activeFilter.label;
  }

  String _filePeriodLabel(ProfitLossState state) {
    final now = DateTime.now();
    switch (state.activeFilter) {
      case ReportsDateFilter.today:
        return '${now.year}_${_twoDigits(now.month)}_${_twoDigits(now.day)}';
      case ReportsDateFilter.thisWeek:
        return 'Week_${now.year}_${_twoDigits(now.month)}_${_twoDigits(now.day)}';
      case ReportsDateFilter.thisMonth:
        return '${_monthName(now.month)}_${now.year}';
      case ReportsDateFilter.thisYear:
        return 'Year_${now.year}';
      case ReportsDateFilter.custom:
        if (state.customFrom != null && state.customTo != null) {
          return '${_dateForFile(state.customFrom!)}_to_${_dateForFile(state.customTo!)}';
        }
        return 'Custom';
    }
  }

  String _date(DateTime value) =>
      '${_twoDigits(value.day)}/${_twoDigits(value.month)}/${value.year}';

  String _dateForFile(DateTime value) =>
      '${value.year}_${_twoDigits(value.month)}_${_twoDigits(value.day)}';

  String _timestamp(DateTime value) =>
      '${_date(value)} ${_twoDigits(value.hour)}:${_twoDigits(value.minute)}';

  String _twoDigits(int value) => value.toString().padLeft(2, '0');

  String _monthName(int month) => const <String>[
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
      ][month - 1];
}
